DROP TABLE IF EXISTS `altset`. `altRecords`;
CREATE TABLE `altRecords` (
`ID` int(11) AUTO INCRAMENT,
`LABEL` VARCHAR (50) NOT NULL,
`FILENAME` VARCHAR (50) NOT NULL,
`LATITUDE` VARCHAR (50) NOT NULL,
`LONGITUDE` VARCHAR (50) NOT NULL,
FOREIGN KEY (ID);
)